FILTERED_SOURCES = [
    '/s/contributor/omcs/bntman',
    '/s/contributor/omcs/cyberguy',
    '/s/contributor/omcs/ddiblasi',
    '/s/contributor/omcs/glneumiller',
    '/s/contributor/omcs/imn8xtc',
    '/s/contributor/omcs/holyrobot',
    '/s/contributor/omcs/lbeckwith',
    '/s/contributor/omcs/maliki',
    '/s/contributor/omcs/sarcastro98',
    '/s/contributor/omcs/wellner',
    '/s/activity/omcs/20_questions',
    '/s/activity/omcs/picture_description',
    '/s/activity/omcs/response_to_diagram',
    '/s/activity/omcs/pycommons_question',
]
