JSON_DEPENDENCIES = raw_data/conceptnet_zh_api.txt raw_data/conceptnet_zh_part1.txt raw_data/conceptnet_zh_part2.txt raw_data/conceptnet_zh_part3.txt raw_data/conceptnet_zh_part4.txt raw_data/conceptnet_zh_part5.txt raw_data/conceptnet_zh_part6.txt raw_data/conceptnet_zh_part7.txt raw_data/conceptnet_zh_part8.txt raw_data/conceptnet_zh_part9.txt raw_data/conceptnet_zh_part10.txt raw_data/conceptnet_zh_part11.txt raw_data/conceptnet_zh_part12.txt


conceptnet_zh_json: $(REVERB_DEPENDENCIES)
	python read_zh.py

