from conceptnet5.languages import ALL_LANGUAGES, get_language_name


LANGUAGE_NAMES = {
    'en': 'English',
    'fr': 'French',
    'de': 'German',
    'it': 'Italian',
    'es': 'Spanish',
    'ru': 'Russian',
    'pt': 'Portuguese',
    'ja': 'Japanese',
    'zh': 'Chinese',
    'nl': 'Dutch',
    'fi': 'Finnish',
    'pl': 'Polish',
    'bg': 'Bulgarian',
    'sv': 'Swedish',
    'cs': 'Czech',
    'sh': 'Serbo-Croatian',
    'sl': 'Slovenian',
    'ar': 'Arabic',
    'ca': 'Catalan',
    'hu': 'Hungarian',
    'se': 'Northern Sami',
    'is': 'Icelandic',
    'ro': 'Romanian',
    'el': 'Greek',
    'lv': 'Latvian',
    'ms': 'Malay',
    'id': 'Indonesian',
    'tr': 'Turkish',
    'da': 'Danish',
    'ga': 'Irish',
    'vi': 'Vietnamese',
    'ko': 'Korean',
    'hy': 'Armenian',
    'gl': 'Galician',
    'oc': 'Occitan',
    'fo': 'Faroese',
    'gd': 'Scottish Gaelic',
    'fa': 'Persian',
    'ast': 'Asturian',
    'hsb': 'Upper Sorbian',
    'ka': 'Georgian',
    'he': 'Hebrew',
    'no': 'Norwegian',
    'sq': 'Albanian',
    'mg': 'Malagasy',
    'nrf': 'Jèrriais',
    'sk': 'Slovak',
    'lt': 'Lithuanian',
    'et': 'Estonian',
    'te': 'Telugu',
    'mk': 'Macedonian',
    'nv': 'Navajo',
    'hi': 'Hindi',
    'ur': 'Urdu',
    'af': 'Afrikaans',
    'sa': 'Sanskrit',
    'th': 'Thai',
    'fil': 'Filipino',
    'eu': 'Basque',
    'rup': 'Aromanian',
    'uk': 'Ukrainian',
    'cy': 'Welsh',
    'be': 'Belarusian',
    'ta': 'Tamil',
    'ku': 'Kurdish',
    'az': 'Azerbaijani',
    'kk': 'Kazakh',
    'sw': 'Swahili',
    'la': 'Latin',
    'grc': 'Ancient Greek',
    'xcl': 'Classical Armenian',
    'fro': 'Old French',
    'ang': 'Old English',
    'non': 'Old Norse',
    'gv': 'Manx',
    'mul': 'Multilingual',
    'eo': 'Esperanto',
    'io': 'Ido',
    'vo': 'Volapük',
    'rm': 'Romansh',
    'br': 'Breton',
    'lb': 'Luxembourgish',
    'fy': 'Western Frisian',
    'frp': 'Arpitan',
    'mi': 'Maori',
    'yi': 'Yiddish',
    'dsb': 'Lower Sorbian',
    'vec': 'Venetian',
    'ln': 'Lingala',
    'fur': 'Friulian',
    'pap': 'Papiamento',
    'nds': 'Low German',
    'mn': 'Mongolian',
    'km': 'Khmer',
    'ba': 'Bashkir',
    'os': 'Ossetic',
    'sco': 'Scots',
    'lld': 'Ladin',
    'bn': 'Bangla',
    'mt': 'Maltese',
    'ady': 'Adyghe',
    'qu': 'Quechua',
    'scn': 'Sicilian',
    'haw': 'Hawaiian',
    'bm': 'Bambara',
    'iu': 'Inuktitut',
    'lo': 'Lao',
    'crh': 'Crimean Turkish',
    'ses': 'Koyraboro Senni',
    'tg': 'Tajik',
    'vep': 'Veps',
    'wa': 'Walloon',
    'kw': 'Cornish',
    'co': 'Corsican',
    'tt': 'Tatar',
    'ky': 'Kyrgyz',
    'ceb': 'Cebuano',
    'nan': 'Min Nan Chinese',
    'dlm': 'Dalmatian',
    'mdf': 'Moksha',
    'stq': 'Saterland Frisian',
    'uz': 'Uzbek',
    'pcd': 'Picard',
    'my': 'Burmese',
    'zu': 'Zulu',
    'sc': 'Sardinian',
    'tk': 'Turkmen',
    'ht': 'Haitian Creole',
    'lad': 'Ladino',
    'arn': 'Mapuche',
    'srn': 'Sranan Tongo',
    'ps': 'Pashto',
    'gu': 'Gujarati',
    'kl': 'Kalaallisut',
    'mr': 'Marathi',
    'tpi': 'Tok Pisin',
    'hil': 'Hiligaynon',
    'kn': 'Kannada',
    'ne': 'Nepali',
    'wym': 'Wymysorys',
    'ug': 'Uyghur',
    'nap': 'Neapolitan',
    'oj': 'Ojibwa',
    'mwl': 'Mirandese',
    'frr': 'Northern Frisian',
    'an': 'Aragonese',
    'yua': 'Yucateco',
    'cv': 'Chuvash',
    'bo': 'Tibetan',
    'zdj': 'Ngazidja Comorian',
    'chr': 'Cherokee',
    'sah': 'Sakha',
    'pal': 'Pahlavi',
    'ce': 'Chechen',
    'wo': 'Wolof',
    'li': 'Limburgish',
    'ml': 'Malayalam',
    'egl': 'Emilian',
    'csb': 'Kashubian',
    'ist': 'Istriot',
    'lkt': 'Lakota',
    'pi': 'Pali',
    'kbd': 'Kabardian',
    'twf': 'Northern Tiwa',
    'jv': 'Javanese',
    'fon': 'Fon',
    'nah': 'Nahuatl languages',
    'pa': 'Punjabi',
    'myv': 'Erzya',
    'nmn': 'ǃXóõ',
    'rom': 'Romany',
    'ltg': 'Latgalian',
    'ee': 'Ewe',
    'sm': 'Samoan',
    'am': 'Amharic',
    'kum': 'Kumyk',
    'krc': 'Karachay-Balkar',
    'gsw': 'Swiss German',
    'dak': 'Dakota',
    'swb': 'Comorian',
    'bal': 'Baluchi',
    'si': 'Sinhala',
    'so': 'Somali',
    'su': 'Sundanese',
    'kjh': 'Khakas',
    'cic': 'Chickasaw',
    'gag': 'Gagauz',
    'nog': 'Nogai',
    'chk': 'Chuukese',
    'ha': 'Hausa',
    'tyv': 'Tuvinian',
    'nhn': 'Central Nahuatl',
    'zza': 'Zaza',
    'oma': 'Omaha-Ponca',
    'vot': 'Votic',
    'krl': 'Karelian',
    'rw': 'Kinyarwanda',
    'aa': 'Afar',
    'or': 'Odia',
    'alt': 'Southern Altai',
    'esu': 'Central Yupik',
    'ccc': 'Chamicuro',
    'ab': 'Abkhazian',
    'ppl': 'Pipil',
    'chl': 'Cahuilla',
    'ain': 'Ainu',
    'na': 'Nauru',
    'ty': 'Tahitian',
    'wau': 'Waurá',
    'dua': 'Duala',
    'rap': 'Rapanui',
    'adx': 'Amdo Tibetan',
    'cjs': 'Shor',
    'tet': 'Tetum',
    'kim': 'Karagas',
    'hak': 'Hakka Chinese',
    'lij': 'Ligurian',
    'gn': 'Guarani',
    'tpw': 'Tupí',
    'sms': 'Skolt Sami',
    'xmf': 'Mingrelian',
    'smn': 'Inari Sami',
    'raj': 'Rajasthani',
    'cim': 'Cimbrian',
    'rue': 'Rusyn',
    'hke': 'Hunde',
    'fj': 'Fijian',
    'pms': 'Piedmontese',
    'wae': 'Walser',
    'yo': 'Yoruba',
    'mh': 'Marshallese',
    'szl': 'Silesian',
    'pjt': 'Pitjantjatjara',
    'khb': 'Lü',
    'dv': 'Divehi',
    'udm': 'Udmurt',
    'dje': 'Zarma',
    'ilo': 'Iloko',
    'aii': 'Assyrian Neo-Aramaic',
    'koy': 'Koyukon',
    'war': 'Waray',
    'lmo': 'Lombard',
    'ti': 'Tigrinya',
    'av': 'Avaric',
    'mch': 'Maquiritari',
    'abe': 'Western Abnaki',
    'cho': 'Choctaw',
    'xwo': 'Written Oirat',
    'za': 'Zhuang',
    'ki': 'Kikuyu',
    'lzz': 'Laz',
    'sd': 'Sindhi',
    'st': 'Southern Sotho',
    'shh': 'Shoshoni',
    'bi': 'Bislama',
    'ch': 'Chamorro',
    'akz': 'Alabama',
    'ff': 'Fulah',
    'xh': 'Xhosa',
    'ii': 'Sichuan Yi',
    'syc': 'Classical Syriac',
    'cu': 'Church Slavic',
    'goh': 'Old High German',
    'frm': 'Middle French',
    'enm': 'Middle English',
    'sga': 'Old Irish',
    'pro': 'Old Provençal',
    'osx': 'Old Saxon',
    'got': 'Gothic',
    'hbo': 'Ancient Hebrew',
    'nci': 'Classical Nahuatl',
    'arc': 'Aramaic',
    'sux': 'Sumerian',
    'ota': 'Ottoman Turkish',
    'dum': 'Middle Dutch',
    'gml': 'Middle Low German',
    'gmh': 'Middle High German',
    'ofs': 'Old Frisian',
    'osp': 'Old Spanish',
    'roa-opt': 'Old Portuguese',
    'prg': 'Prussian',
    'liv': 'Livonian',
    'egx': 'Egyptian languages',
    'akk': 'Akkadian',
    'odt': 'Old Dutch',
    'oge': 'Old Georgian',
    'frk': 'Frankish',
    'axm': 'Middle Armenian',
    'txb': 'Tokharian B',
    'orv': 'Old Russian',
    'xto': 'Tokharian A',
    'peo': 'Old Persian',
    'ae': 'Avestan',
    'xno': 'Anglo-Norman',
    'uga': 'Ugaritic',
    'mga': 'Middle Irish',
    'egy': 'Ancient Egyptian',
    'xpr': 'Parthian',
    'cop': 'Coptic',
    'hit': 'Hittite',
    'jbo': 'Lojban',
    'ia': 'Interlingua',
    'nov': 'Novial',
    'ie': 'Interlingue',
    'qya': 'Quenya',
}


# If the display name of a language changes, we should know about it
def test_language_names():
    for code in LANGUAGE_NAMES:
        name = get_language_name(code)
        assert name == LANGUAGE_NAMES[code]
