REL_HEADINGS = {
    'en': {
        '/r/SimilarTo': ['Similar terms'],
        '/r/RelatedTo': ['Related terms'],
        '/r/Synonym': ['Synonyms'],
        '/r/Antonym': ['Antonyms'],
        '/r/FormOf': ['Word forms', 'Root words'],
        '/r/HasContext': ['Terms with this context', 'Context of this term'],
        '/r/DerivedFrom': ['Derived terms', 'Derived from'],
        '/r/IsA': ['Types of {0}', '{0} is a type of…'],
        '/r/EtymologicallyRelatedTo': ['Etymologically related'],
        '/r/EtymologicallyDerivedFrom': ['Etymologically derived terms', 'Etymological roots of "{0}"'],
        '/r/AtLocation': ['Things located at {0}', 'Location of {0}'],
        '/r/Causes': ['Causes of {0}', 'Effects of {0}'],
        '/r/UsedFor': ['Things used for {0}', '{0} is used for…'],
        '/r/NotUsedFor': ['Things that are not used for {0}', '{0} is not used for…'],
        '/r/MotivatedByGoal': ['Things motivated by {0}', '{0} is motivated by…'],
        '/r/HasSubevent': ['Subevents of {0}', '{0} is a subevent of…'],
        '/r/DistinctFrom': ['Distinct terms'],
        '/r/CapableOf': ['Things capable of {0}', '{0} is capable of…'],
        '/r/NotCapableOf': ['Things incapable of {0}', '{0} is not capable of…'],
        '/r/Desires': ['Things that want {0}', '{0} wants…'],
        '/r/NotDesires': ["Things that don't want {0}", "{0} doesn't want…"],
        '/r/PartOf': ['Parts of {0}', '{0} is part of…'],
        '/r/HasPrerequisite': ['Things that require {0}', '{0} requires…'],
        '/r/CausesDesire': ['Things that make you want {0}', '{0} makes you want…'],
        '/r/HasProperty': ['Things with the property {0}', 'Properties of {0}'],
        '/r/MadeOf': ['Things made of {0}', '{0} is made of…'],
        '/r/HasFirstSubevent': ['Things whose first step is {0}', '{0} is the first step of…'],
        '/r/HasLastSubevent': ['Things whose last step is {0}', '{0} is the last step of…'],
        '/r/DefinedAs': ['Things defined as {0}', '{0} is defined as…'],
        '/r/ReceivesAction': ['Things that can be {0}', '{0} can be…'],
        '/r/HasA': ['Things with {0}', '{0} has…'],
        '/r/SymbolOf': ['Symbols of {0}', '{0} symbolizes…'],
        '/r/ObstructedBy': ['{0} obstructs…', '{0} is obstructed by…'],
        '/r/Entails': ['Things that entail {0}', '{0} entails…'],
        '/r/CreatedBy': ['Things created by {0}', '{0} is created by…'],
        '/r/MannerOf': ['Ways of {0}', '{0} is a way of…'],
        '/r/LocationOfAction': ['Places where {0} happens', '{0} happens at…'],
        '/r/Uses': ['Things that use {0}', '{0} uses…'],
        '/r/ControlledBy': ['{0} controls…', '{0} is controlled by…'],
        '/r/LocatedNear': ['Things located near {0}', '{0} is near…'],
        '/r/ExternalURL': ['Links to ConceptNet', 'Links to other sites'],
        '/r/dbpedia/field': ['In the field of {0}', '{0} is in the field of…'],
        '/r/dbpedia/genre': ['In the genre of {0}', '{0} is in the genre of…'],
        '/r/dbpedia/knownFor': ['People known for {0}', '{0} is known for…'],
        '/r/dbpedia/product': ['Makers of {0}', '{0} makes the product…'],
        '/r/dbpedia/occupation': ['People with the occupation {0}', 'Occupation of {0}'],
        '/r/dbpedia/language': ['Things whose language is {0}', 'Language of {0}'],
        '/r/dbpedia/influencedBy': ['{0} influenced…', '{0} was influenced by…'],
        '/r/dbpedia/capital': ['{0} is the capital of…', 'Capital of {0}'],
        '/r/dbpedia/leader': ['{0} has led…', '{0} has been led by…'],
        '/r/dbpedia/genus': ['Species of {0}', '{0} is a species of…'],
    }
}
